databases:
  - name: ttcdb
    plan: basic-256mb
    databaseName: mydatabase
    user: myuser

services:
  - type: web
    plan: free
    name: ttc
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd the_tuesday_club_server/ttc && python -m gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ttcdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4