# Generated by Django 5.1.2 on 2024-10-28 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
                ('album_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PileStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pile_status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('image_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('album_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album_image', to='myapp.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(db_column='label_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.label'),
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_id', models.CharField(max_length=255)),
                ('pile_start_date', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pile_status', models.ForeignKey(db_column='pile_status_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.pilestatus')),
            ],
            options={
                'unique_together': {('pile_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PileItem',
            fields=[
                ('album', models.OneToOneField(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.album')),
                ('added_to_pile', models.DateTimeField()),
                ('pile_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pile', models.OneToOneField(db_column='pile_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.pile')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_start_date', models.IntegerField()),
                ('album_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.album')),
            ],
            options={
                'unique_together': {('album', 'price_start_date')},
            },
        ),
    ]
