# Generated by Django 5.1.2 on 2024-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumeancode',
            name='album_ean_code',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='albumupc',
            name='album_upc',
            field=models.BigIntegerField(unique=True),
        ),
    ]
