# Generated by Django 5.1.2 on 2024-11-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_add_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
