# Generated by Django 5.1.2 on 2024-12-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pileitem_quantity_alter_address_user_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW unsent_pile_items_view AS
            SELECT
                concat(myapp_pile.pile_id,'_',myapp_pileitem.album_id) AS unique_key,
                myapp_pileitem.pile_item_id,
                myapp_pileitem.album_id,
                myapp_album.album_name,
                myapp_pileitem.quantity,
                myapp_pileitem.pile_item_price AS price,
                myapp_pileitem.added_to_pile,
                myapp_pile.pile_id,
                myapp_pilestatus.pile_status_name AS pile_status,
                myapp_pile.user_id
                FROM
                (
                (
                    (
                        myapp_pileitem
                        JOIN myapp_pile ON ((myapp_pileitem.pile_id = myapp_pile.pile_id))
                    )
                    JOIN myapp_pilestatus ON ((myapp_pile.pile_status_id = myapp_pilestatus.id))
                )
                JOIN myapp_album ON ((myapp_pileitem.album_id = myapp_album.album_id))
                )
                WHERE ((myapp_pilestatus.pile_status_name)::text <> 'afsendt'::text)
            """
        )
    ]
