# Generated by Django 5.1.2 on 2024-12-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_unsent_pile_items_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsentPileItem',
            fields=[
                ('unique_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pile_item_id', models.UUIDField()),
                ('album_id', models.UUIDField()),
                ('album_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_to_pile', models.DateTimeField()),
                ('pile_id', models.UUIDField()),
                ('pile_status', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'unsent_pile_items_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
