# Generated by Django 5.1.2 on 2024-12-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_update_album_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='image_name',
        ),
    ]
