# Generated by Django 5.1.2 on 2024-12-08 12:28

import django.core.validators
import django.db.models.deletion
import project.custom_storages
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlbumView',
            fields=[
                ('album_id', models.UUIDField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_units', models.IntegerField(blank=True, null=True)),
                ('album_format_id', models.IntegerField(blank=True, null=True)),
                ('format_name', models.CharField(max_length=50)),
                ('label_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_start_date', models.DateField(blank=True, null=True)),
                ('album_ean_code', models.BigIntegerField(blank=True, null=True)),
                ('album_upc', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_album_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumView',
            fields=[
                ('album_id', models.UUIDField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_units', models.IntegerField(blank=True, null=True)),
                ('album_format_id', models.IntegerField(blank=True, null=True)),
                ('format_name', models.CharField(blank=True, max_length=50, null=True)),
                ('label_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_start_date', models.DateField(blank=True, null=True)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'album_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnsentPileItem',
            fields=[
                ('unique_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pile_item_id', models.UUIDField()),
                ('album_id', models.UUIDField()),
                ('album_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_to_pile', models.DateTimeField()),
                ('pile_id', models.UUIDField()),
                ('pile_status', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'unsent_pile_items_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_format', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_additional_info', models.CharField(max_length=255)),
                ('album_id', models.OneToOneField(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumEANcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_ean_code', models.BigIntegerField(unique=True)),
                ('album_id', models.OneToOneField(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, storage=project.custom_storages.MediaStorage(), upload_to='uploads/')),
                ('album_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album_image', to='core.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumReleaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_year', models.DateField()),
                ('album_id', models.OneToOneField(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumUnitFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_units', models.CharField(max_length=255)),
                ('album_format_id', models.ForeignKey(db_column='album_format_id', on_delete=django.db.models.deletion.CASCADE, to='core.albumformat')),
                ('album_id', models.OneToOneField(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumUPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_upc', models.BigIntegerField(unique=True)),
                ('album_id', models.OneToOneField(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='core.artist'),
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('genre_id', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='label_id',
            field=models.ForeignKey(db_column='label_id', on_delete=django.db.models.deletion.CASCADE, to='core.label'),
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('pile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pile_start_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pile_status', models.ForeignKey(db_column='pile_status_id', on_delete=django.db.models.deletion.CASCADE, to='core.pilestatus')),
            ],
            options={
                'unique_together': {('pile_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='AlbumPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_start_date', models.DateField()),
                ('album_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album_id', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
            options={
                'unique_together': {('album_id', 'price_start_date')},
            },
        ),
        migrations.CreateModel(
            name='PileItem',
            fields=[
                ('pile_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_to_pile', models.DateTimeField()),
                ('pile_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('album_id', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('pile_id', models.ForeignKey(db_column='pile_id', on_delete=django.db.models.deletion.CASCADE, to='core.pile')),
            ],
            options={
                'unique_together': {('pile_id', 'album_id')},
            },
        ),
    ]
