# Generated by Django 5.1.2 on 2024-12-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE OR REPLACE VIEW album_view AS
                SELECT
                album.album_id,
                album.album_name,
                artist.artist_name,
                albumunitformat.album_units,
                albumunitformat.album_format_id,
                CASE WHEN (lower((albumformat.album_format)::text) = 'lp'::text) THEN 'LP'::character varying WHEN (lower((albumformat.album_format)::text) = ANY (ARRAY['12"'::text,'12in'::text])) THEN '12in'::character varying WHEN (lower((albumformat.album_format)::text) = 'vinyl with cd'::text) THEN 'LP with CD'::character varying WHEN (lower((albumformat.album_format)::text) = ANY (ARRAY['7"'::text,'7in'::text,'v7'::text])) THEN '7in'::character varying WHEN (lower((albumformat.album_format)::text) = 'mc'::text) THEN 'Music Cassette'::character varying ELSE albumformat.album_format END AS format_name,
                label.label_name,
                albumprice.album_price,
                albumprice.price_start_date,
                albumimage.image AS album_image
                FROM
                (
                (
                    (
                        (
                            (
                            (
                                core_album album
                                LEFT JOIN core_artist artist ON
                                (
                                    (album.artist_id = artist.artist_id)
                                )
                            )
                            LEFT JOIN core_albumunitformat albumunitformat ON
                            (
                                (album.album_id = albumunitformat.album_id)
                            )
                            )
                            LEFT JOIN core_albumformat albumformat ON
                            (
                            (albumunitformat.album_format_id = albumformat.id)
                            )
                        )
                        LEFT JOIN core_label label ON ((album.label_id = label.label_id))
                    )
                    LEFT JOIN core_albumprice albumprice ON
                    (
                        (album.album_id = albumprice.album_id)
                    )
                )
                LEFT JOIN core_albumimage albumimage ON
                (
                    (
                        (album.album_id = albumimage.album_id_id)
                        AND
                        (
                            albumprice.price_start_date =
                            (
                            SELECT
                            max(ap.price_start_date) AS max
                            FROM core_albumprice ap
                            WHERE (ap.album_id = album.album_id)
                            )
                        )
                    )
                )
                )
            """
        )
    ]
