# Generated by Django 5.1.2 on 2024-12-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_album_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='pile_status',
            field=models.CharField(choices=[('open', 'Åben'), ('closed', 'Lukket'), ('ordered', 'Bestilt'), ('received', 'Modtaget'), ('sent', 'Afsendt')], db_column='pile_status_id'),
        ),
        migrations.DeleteModel(
            name='PileStatus',
        ),
    ]
