# Generated by Django 5.1.2 on 2024-12-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pile_pile_status_delete_pilestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='pile_status',
            field=models.CharField(choices=[('open', 'Åben'), ('closed', 'Lukket'), ('ordered', 'Bestilt'), ('received', 'Modtaget'), ('sent', 'Afsendt')]),
        ),
    ]
