# Generated by Django 5.1.2 on 2024-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_historicaluser_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpile',
            name='pile_status',
        ),
        migrations.RemoveField(
            model_name='pile',
            name='pile_status',
        ),
        migrations.AddField(
            model_name='historicalpileitem',
            name='pile_status',
            field=models.CharField(choices=[('open', 'Åben'), ('closed', 'Lukket'), ('ordered', 'Bestilt'), ('received', 'Modtaget'), ('sent', 'Afsendt')], default='open'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pileitem',
            name='pile_status',
            field=models.CharField(choices=[('open', 'Åben'), ('closed', 'Lukket'), ('ordered', 'Bestilt'), ('received', 'Modtaget'), ('sent', 'Afsendt')], default='open'),
            preserve_default=False,
        ),
    ]
