# Generated by Django 5.1.2 on 2024-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_historicalpile_pile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='fetch_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
