# Generated by Django 5.1.2 on 2024-12-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fetch_status_on_album_viwe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAlbumView',
        ),
    ]
